services:
  exporter:
    command:
      - --web.listen-address=:9853
      - --${FEATURE_NAME:-domain}.config-file=${FEATURE_CONFIG_CONTAINER_PATH:-/etc/prometheus/prometheus-domain-exporter.yml}
      - --${FEATURE_NAME:-domain}.refresh-interval=1h
      - --${FEATURE_NAME:-domain}.target=example.com
      - --${FEATURE_NAME:-domain}.target=example.net
